export const Roles = {
  ROLE_HR: "ROLE_HR",
  ROLE_EMPLOYEE: "ROLE_EMPLOYEE",
  ROLE_MANAGER: "ROLE_MANAGER",
  ROLE_VIEWER: "ROLE_VIEWER",
  SUPER_ADMIN: "SUPER_ADMIN",
  ROLE_RECRUITER: "ROLE_RECRUITER",
};
